"""Timing counterpart to the correctness oracle.

`generate.py` establishes that our studies agree with pandas bar-for-bar.
This establishes how fast pandas is at the same work, so "as fast as
possible" has a reference point that isn't our own previous commit.

pandas is the right yardstick here and not a straw man: `rolling().mean()`
and `rolling().std()` are implemented in Cython over contiguous numpy
buffers with the same O(1)-per-bar incremental algorithms, and it is what
the practitioners this library is for would otherwise reach for.

**Conventions match the oracle** so the comparison is like for like — the
same definitions `generate.py` pins:
  - `min_periods=period` (length-preserving warm-up, NaN head)
  - `ddof=0` (population standard deviation)
  - the same bollinger / z-score / envelope / percent-change formulas

Emits JSON so `perf-vs-oracle.mjs` can join it against the TypeScript run.

Run:
    /tmp/pondvenv/bin/python packages/financial/scripts/oracle/perf-compare.py
"""

import json
import os
import time

import numpy as np
import pandas as pd

BARS = int(os.environ.get("PERF_BARS", 500_000))
REPEATS = int(os.environ.get("PERF_REPEATS", 15))
MINUTE_NS = 60_000_000_000


def make_bars(n: int) -> pd.DataFrame:
    """The same random walk the TypeScript benchmark builds, generated by the
    same mulberry32 sequence so both sides see identical numbers."""
    seed = 0x5EED
    out = np.empty(n, dtype=np.float64)
    highs = np.empty(n, dtype=np.float64)
    lows = np.empty(n, dtype=np.float64)
    opens = np.empty(n, dtype=np.float64)
    vols = np.empty(n, dtype=np.float64)

    def rnd() -> float:
        nonlocal seed
        seed = (seed + 0x6D2B79F5) & 0xFFFFFFFF
        t = (seed ^ (seed >> 15)) * (1 | seed) & 0xFFFFFFFF
        t = (t + ((t ^ (t >> 7)) * (61 | t) & 0xFFFFFFFF)) & 0xFFFFFFFF
        t = t ^ t
        # Mirrors the JS generator closely enough for a timing workload; the
        # exact values do not matter here, only the shape and the size.
        seed2 = (seed * 1103515245 + 12345) & 0x7FFFFFFF
        return seed2 / 0x7FFFFFFF

    price = 100.0
    for i in range(n):
        drift = (rnd() - 0.5) * 0.4
        o = price
        c = max(1.0, price + drift)
        opens[i] = o
        out[i] = c
        highs[i] = max(o, c) + rnd() * 0.2
        lows[i] = min(o, c) - rnd() * 0.2
        vols[i] = int(rnd() * 10_000)
        price = c

    index = pd.to_datetime(np.arange(n, dtype=np.int64) * MINUTE_NS)
    return pd.DataFrame(
        {"open": opens, "high": highs, "low": lows, "close": out, "volume": vols},
        index=index,
    )


def bench(label: str, group: str, fn, repeats: int = REPEATS) -> dict:
    # pandas has no JIT to warm, but the first call still pays lazy imports
    # and allocator warm-up. A few untimed passes keeps that out of the median.
    for _ in range(3):
        fn()
    samples = []
    for _ in range(repeats):
        start = time.perf_counter()
        fn()
        samples.append((time.perf_counter() - start) * 1000.0)
    samples.sort()
    return {
        "group": group,
        "label": label,
        "medianMs": round(samples[len(samples) // 2], 3),
        "minMs": round(samples[0], 3),
        "maxMs": round(samples[-1], 3),
    }


def main() -> None:
    df = make_bars(BARS)
    close = df["close"]
    results = []

    def sma(period: int):
        return close.rolling(period, min_periods=period).mean()

    def ema(period: int):
        # `adjust=False` + a warm-up gate, matching the oracle's convention.
        out = close.ewm(span=period, adjust=False).mean()
        out.iloc[: period - 1] = np.nan
        return out

    def bollinger(period: int, k: float = 2.0):
        r = close.rolling(period, min_periods=period)
        middle = r.mean()
        sd = r.std(ddof=0)
        return middle, middle + k * sd, middle - k * sd

    def zscore(period: int):
        r = close.rolling(period, min_periods=period)
        return (close - r.mean()) / r.std(ddof=0)

    def pct_change():
        return close.pct_change() * 100.0

    def envelope(period: int, pct: float = 0.02):
        middle = close.rolling(period, min_periods=period).mean()
        return middle, middle * (1 + pct), middle * (1 - pct)

    for label, fn in [
        ("sma(20)", lambda: sma(20)),
        ("sma(200)", lambda: sma(200)),
        ("ema(20)", lambda: ema(20)),
        ("bollinger(20)", lambda: bollinger(20)),
        ("zScore(20)", lambda: zscore(20)),
        ("percentChange()", lambda: pct_change()),
        ("envelope(20)", lambda: envelope(20)),
    ]:
        results.append(bench(label, "study", fn))

    def stack():
        out = df.copy()
        out["sma20"] = sma(20)
        out["sma50"] = sma(50)
        out["sma200"] = sma(200)
        m, u, lo = bollinger(20)
        out["bbMiddle"], out["bbUpper"], out["bbLower"] = m, u, lo
        out["zscore"] = zscore(20)
        return out

    results.append(
        bench("stack: sma20+sma50+sma200+bollinger+zscore", "strategy", stack, 5)
    )

    for label, fn in [
        ("close.minMax()", lambda: (close.min(), close.max())),
        ("close.mean()", lambda: close.mean()),
        ("close.stdev()", lambda: close.std(ddof=0)),
        ("close.median()", lambda: close.median()),
        ("close.percentile(95)", lambda: close.quantile(0.95)),
        (
            "volume.sum() + close.minMax()",
            lambda: (df["volume"].sum(), close.min(), close.max()),
        ),
    ]:
        results.append(bench(label, "summary", fn, 25))

    print(
        json.dumps(
            {
                "bars": BARS,
                "pandas": pd.__version__,
                "numpy": np.__version__,
                "results": results,
            },
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
