import { TimeSeries } from 'pond-ts';
import { TradingCalendar } from '@pond-ts/financial';

/**
 * **MODELLED, not measured.** Every price and volume below is generated by the
 * process model in this file. No market data is redistributed here, and none
 * should be inferred from it.
 *
 * 1. **What it is** — **251** daily OHLCV bars, one per session of a
 *    US-equity-style trading year (2025-08-01 → 2026-07-31), for a fictional
 *    instrument ("ACME"). Prices are dollars, volume is shares. This
 *    realization runs $147.34 → $155.86 (+5.8% on the year), low $132.68, high
 *    $173.38, with a **−23.5% peak-to-trough drawdown** (2025-12-01 →
 *    2026-04-22), a 1.44% daily return standard deviation, and a worst session
 *    of −7.5%. Median volume 4.08 M shares, peaking at 13.34 M.
 * 2. **Where it came from, and the licence** — nowhere: it is generated, by
 *    {@link buildBars} below, from a seeded PRNG. Market price data is the
 *    sharp licensing case for a docs site — essentially every feed forbids
 *    redistribution — so the Gallery's finance cards are **tier 3** of the
 *    fixture policy (`README.md` → "Modelled data says so, loudly"). The one
 *    thing here that _is_ real is the **session calendar**: NYSE hours
 *    (09:30–16:00 America/New_York), the 2025-26 US market holidays, and the
 *    two 13:00 half-days. Public holiday dates are facts, not a licensed feed.
 * 3. **What was kept, and what was dropped** — a bar carries `open`, `high`,
 *    `low`, `close` and `volume`. There is no bid/ask, no trade count, no
 *    adjusted close and no corporate-action history; none is needed to draw
 *    the four Gallery cards, and modelling them convincingly would be four
 *    more chances to be caught pretending.
 * 4. **The quirks that are there on purpose** — these are what separate a
 *    modelled series from a sine wave, and each is visible in the charts:
 *    - **Sessions, not days.** Weekends and the ten holidays simply have no
 *      bar. The gaps are in the data, so a plain time axis shows them and a
 *      `TradingCalendar` axis collapses them — same series, different axis.
 *    - **Opening gaps.** A bar's `open` is _not_ the previous `close`: the
 *      overnight return is drawn separately, so bars gap up and down. Median
 *      absolute gap 0.45%, largest 3.20%, and 40 of 250 gap by more than 1%.
 *    - **Volatility clustering.** Returns come from a GARCH(1,1)-shaped
 *      variance, so a big move makes the next few days bigger too, plus
 *      occasional fat-tailed jumps. Quiet fortnights and violent ones.
 *    - **Regimes.** A run-up, a sharp correction with a volatility spike, a
 *      choppy recovery, a shallower second dip, then a grind back. That's
 *      what gives the drawdown card something to be about.
 *    - **Volume responds to price.** It rises with the size of the day's move
 *      _and_ stays elevated for several sessions afterwards — the −7.5%
 *      session of 2026-03-23 trades 12.9 M against a 4.08 M median (3.2×),
 *      and the following week stays heavy. Volume also scales with the
 *      session's **actual length**, so the two 13:00 half-days are multiplied
 *      by (3.5 / 6.5)^0.9 ≈ 0.58 — they print 3.27 M and 3.36 M, below the
 *      median despite both landing in otherwise busy weeks.
 * 5. **How it was made** — inline, at import time, from `mulberry32(…)`;
 *    never `Math.random()` or `Date.now()`, so the server, the client and
 *    every visit produce byte-identical bars. There is no offline generator
 *    script because there is no source to re-pull.
 *
 * ## Swapping in real data
 *
 * This module is deliberately shaped so that arriving market data is a
 * **fixture change, not a rewrite**. Everything the Gallery's finance charts
 * need is behind {@link BarSet}: the instrument's label, the axis formats, the
 * session calendar and the bars. No card hardcodes a symbol, a currency or a
 * date. To swap in a real, redistributable set, build a `BarSet` from it and
 * return that from {@link marketBars} — with `modelled: false`, a real
 * `provenance` line, and the §2c header rules applied to whatever module the
 * bars land in.
 */

// ---------------------------------------------------------------------------
// The shape a finance chart consumes
// ---------------------------------------------------------------------------

/** The daily bar schema — point-keyed at each session's open. */
const barSchema = [
  { name: 'time', kind: 'time' },
  { name: 'open', kind: 'number' },
  { name: 'high', kind: 'number' },
  { name: 'low', kind: 'number' },
  { name: 'close', kind: 'number' },
  { name: 'volume', kind: 'number' },
] as const;

export type BarSchema = typeof barSchema;

/**
 * One instrument's daily bars plus everything a chart needs to label and scale
 * them. The Gallery's four finance cards read only this — which is what makes
 * the dataset swappable (see the module header).
 */
export interface BarSet {
  /** Ticker-ish short label. Cards pass it as `<Candlestick as>`, never a literal. */
  readonly symbol: string;
  /** Human label for prose and legends. */
  readonly name: string;
  /** d3-format for price axes and price readouts — carries the currency. */
  readonly priceFormat: string;
  /** d3-format for volume axes (SI-prefixed: `4.2M`). */
  readonly volumeFormat: string;
  /**
   * The exchange schedule the bars sit on. Pass it to
   * `<ChartContainer calendar>` for a session-aware axis. Built **once** per
   * module load — the container memoizes its gap provider on calendar
   * identity, so a fresh calendar per render would rebuild the x scale every
   * frame.
   */
  readonly calendar: TradingCalendar;
  /** One row per session: `open`/`high`/`low`/`close`/`volume`. */
  readonly bars: TimeSeries<BarSchema>;
  /** `true` when the prices are generated. Pages that draw this say so. */
  readonly modelled: boolean;
  /** One line on where the numbers came from, for a page that wants to print it. */
  readonly provenance: string;
}

// ---------------------------------------------------------------------------
// The session calendar — real hours, real holidays
// ---------------------------------------------------------------------------

/**
 * US market holidays over the fixture's span, and the two early closes. These
 * are calendar facts (they are published, not licensed), and they are the
 * reason the axis has something to collapse beyond weekends.
 */
const HOLIDAYS = [
  '2025-09-01', // Labor Day
  '2025-11-27', // Thanksgiving
  '2025-12-25', // Christmas Day
  '2026-01-01', // New Year's Day
  '2026-01-19', // Martin Luther King Jr. Day
  '2026-02-16', // Presidents' Day
  '2026-04-03', // Good Friday
  '2026-05-25', // Memorial Day
  '2026-06-19', // Juneteenth
  '2026-07-03', // Independence Day (observed — the 4th is a Saturday)
] as const;

/** The 13:00 half-days: the Friday after Thanksgiving, and Christmas Eve. */
const EARLY_CLOSES = [
  { date: '2025-11-28', close: '13:00' },
  { date: '2025-12-24', close: '13:00' },
] as const;

function buildCalendar(): TradingCalendar {
  return TradingCalendar.fromRules(
    {
      timeZone: 'America/New_York',
      open: '09:30',
      close: '16:00',
      holidays: HOLIDAYS,
      earlyCloses: EARLY_CLOSES,
    },
    { from: '2025-08-01', to: '2026-07-31' },
  );
}

// ---------------------------------------------------------------------------
// The process model
// ---------------------------------------------------------------------------

/** A tiny deterministic PRNG (mulberry32) — the house generator. */
function mulberry32(seed: number): () => number {
  let a = seed;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Standard normal draws (Marsaglia polar) off a uniform stream. */
function gaussians(rand: () => number): () => number {
  let spare: number | undefined;
  return () => {
    if (spare !== undefined) {
      const s = spare;
      spare = undefined;
      return s;
    }
    let u = 0;
    let v = 0;
    let q = 0;
    do {
      u = rand() * 2 - 1;
      v = rand() * 2 - 1;
      q = u * u + v * v;
    } while (q === 0 || q >= 1);
    const f = Math.sqrt((-2 * Math.log(q)) / q);
    spare = v * f;
    return u * f;
  };
}

/**
 * The regime schedule, in fractions of the sample so it survives a change of
 * window: a run-up, a sharp correction on doubled volatility, a choppy
 * recovery, a shallower second dip, then a grind back up. Markets trend, break
 * and chop; they do not oscillate on a fixed period, which is exactly what a
 * `sin(i / 7)` fixture gets wrong.
 */
const REGIMES: readonly { until: number; drift: number; vol: number }[] = [
  { until: 0.33, drift: 0.0016, vol: 0.9 },
  { until: 0.42, drift: -0.0082, vol: 2.4 },
  { until: 0.58, drift: 0.0021, vol: 1.5 },
  { until: 0.69, drift: -0.0036, vol: 1.6 },
  { until: 1.01, drift: 0.0015, vol: 0.95 },
];

function regimeAt(t: number): { drift: number; vol: number } {
  for (const r of REGIMES) if (t < r.until) return r;
  return REGIMES[REGIMES.length - 1]!;
}

// GARCH(1,1) constants: ω/(1 − α − β) = 9e-5 ⇒ a ~0.95%/session long-run
// volatility, with α + β = 0.96 so shocks decay over a couple of weeks
// rather than a couple of days. That persistence *is* the clustering.
//
// The variance recursion is fed the **regime-free** innovation, not the
// emitted return. Feeding back the regime-scaled return instead makes the
// effective α during a 2.4×-volatility regime α·2.4² = 0.58, so α + β > 1 and
// the process is explosive — the model diverges to a zero price inside the
// correction. Which is a nice illustration of why the model gets checked
// numerically before it gets drawn.
const GARCH_OMEGA = 3.6e-6;
const GARCH_ALPHA = 0.1;
const GARCH_BETA = 0.86;
const LONG_RUN_SIGMA = Math.sqrt(GARCH_OMEGA / (1 - GARCH_ALPHA - GARCH_BETA));

/** Full-length regular session, in ms — the yardstick half-days scale against. */
const REGULAR_SESSION_MS = 6.5 * 3_600_000;

function buildBars(calendar: TradingCalendar): TimeSeries<BarSchema> {
  const sessions = calendar.sessions();
  // The seed is a **chosen realization**, not a lucky first try: seeds were
  // swept for a path that completes a full cycle inside one year (run-up,
  // −23.5% drawdown, recovery) so the four cards have something to be about.
  // Choosing which sample of a stated model to show is fine; choosing it and
  // implying it was measured is not, which is what the header is for.
  const rand = mulberry32(12);
  const z = gaussians(rand);

  const rows: Array<[number, number, number, number, number, number]> = [];
  let logClose = Math.log(148);
  let variance = LONG_RUN_SIGMA * LONG_RUN_SIGMA;
  let lastShock = 0;
  // An EWMA of "how big was the move, in typical moves" — this is what keeps
  // volume elevated for days after a shock instead of only on the shock.
  let volumePressure = 1;

  for (let i = 0; i < sessions.length; i += 1) {
    const session = sessions[i]!;
    const regime = regimeAt(i / sessions.length);

    variance =
      GARCH_OMEGA + GARCH_ALPHA * lastShock * lastShock + GARCH_BETA * variance;
    // ~4% of sessions are a fat tail — the outsized bar that makes a real
    // chart's scale awkward, and that a Gaussian alone never produces.
    const jump = rand() < 0.04 ? 2.4 : 1;
    const shock = Math.sqrt(variance) * z() * jump;
    lastShock = shock;

    const sigma = Math.sqrt(variance) * regime.vol;
    const dayReturn = regime.drift + regime.vol * shock;

    // The overnight move is drawn on its own, so `open` gaps off the previous
    // `close` instead of touching it. Roughly a third of a day's move happens
    // while the market is shut, which is about what equities do.
    const overnight = 0.3 * dayReturn + 0.5 * sigma * z();
    const logOpen = logClose + overnight;
    logClose = logOpen + (dayReturn - overnight);

    const open = Math.exp(logOpen);
    const close = Math.exp(logClose);
    // Wicks scale with the session's own volatility, so quiet days have small
    // ones and shock days have long ones.
    const upWick = sigma * (0.25 + 1.3 * rand());
    const downWick = sigma * (0.25 + 1.3 * rand());
    const high = Math.max(open, close) * Math.exp(upWick);
    const low = Math.min(open, close) * Math.exp(downWick * -1);

    // Volume has two components: **today's** move (the spike) and a decaying
    // memory of the last few sessions' moves (the elevated week after it).
    // One or the other alone is wrong — a spike with no tail, or a smear with
    // no spike.
    const move = Math.abs(dayReturn) / LONG_RUN_SIGMA;
    volumePressure = 0.72 * volumePressure + 0.28 * move;
    const sessionScale = (session.close - session.open) / REGULAR_SESSION_MS;
    const volume =
      4.1e6 *
      (0.35 + 0.35 * volumePressure + 0.3 * move) *
      Math.exp(0.22 * z()) *
      Math.pow(sessionScale, 0.9);

    rows.push([
      session.open,
      Math.round(open * 100) / 100,
      Math.round(high * 100) / 100,
      Math.round(low * 100) / 100,
      Math.round(close * 100) / 100,
      Math.round(volume / 1000) * 1000,
    ]);
  }

  return new TimeSeries({ name: 'ACME daily', schema: barSchema, rows });
}

// ---------------------------------------------------------------------------
// The dataset
// ---------------------------------------------------------------------------

let cached: BarSet | undefined;

/**
 * The Gallery's finance dataset — a modelled year of daily bars on a real
 * NYSE-shaped session calendar. **Cached**: repeated calls return the same
 * object, so the calendar and the series keep stable identities across the
 * many renders an autoplaying card does (see {@link BarSet.calendar}).
 */
export function marketBars(): BarSet {
  if (cached) return cached;
  const calendar = buildCalendar();
  cached = {
    symbol: 'ACME',
    name: 'Acme Corp.',
    priceFormat: '$,.2f',
    // `~` trims the trailing zeros an SI specifier otherwise pads to a fixed
    // precision — `.2s` renders the zero tick as `0.00M` and a round 5 M tick
    // as `5.00M`, which reads as noise on a short volume axis.
    volumeFormat: '.2~s',
    calendar,
    bars: buildBars(calendar),
    modelled: true,
    provenance:
      'Modelled prices on a real NYSE-shaped session calendar — no market ' +
      'data is redistributed. See src/examples/lib/financial-fixtures.ts.',
  };
  return cached;
}

// ---------------------------------------------------------------------------
// Windows — always expressed in sessions, never in days
// ---------------------------------------------------------------------------

/**
 * A view onto the set: the x range to hand `<ChartContainer range>`, and the
 * bars that fall inside it.
 *
 * **Why the bars come cropped.** A `<YAxis>` with no explicit `min`/`max`
 * auto-fits the union of its layers' `yExtent()`, and a layer's extent is over
 * **every point in the series it was handed** — not the points inside the
 * container's `range`. Draw 60 sessions of a year-long series and the price
 * axis still spans the whole year, so the candles crowd into a third of the
 * row. Cropping the series to the window is the fix, and it's cheap:
 * `slice(from, to)` is a column-native row-range reshape, not a filter pass.
 * (Cropping also means panning past the window's edge shows no data — the
 * trade for an axis that fits. An explicit `<YAxis min max>` is the other way
 * to do it.)
 */
export interface BarWindow {
  /** `[from, to]` for `<ChartContainer range>`. */
  readonly range: [number, number];
  /** The bars inside `range` — see the note above on why they're cropped. */
  readonly bars: TimeSeries<BarSchema>;
}

/**
 * Build the window for session index range `[from, to]`, padding the x range
 * by half a session each side so the end candles' slots are fully in view. A
 * point-keyed slot reaches halfway to a notional neighbour, so an unpadded
 * range clips the first and last candle down the middle — the same padding
 * `Candlestick.stories.tsx`'s `dayRange` helper applies.
 */
function windowOf(set: BarSet, from: number, to: number): BarWindow {
  const sessions = set.calendar.sessions();
  const first = sessions[from]!;
  const last = sessions[to]!;
  const half = (first.close - first.open) / 2;
  return {
    range: [first.open - half, last.open + half],
    bars: set.bars.slice(from, to + 1),
  };
}

/** Every session in the set. */
export function fullWindow(set: BarSet): BarWindow {
  return windowOf(set, 0, set.calendar.length - 1);
}

/**
 * The last `count` sessions — or a window ending `endOffset` sessions before
 * the last one. Session-counted rather than day-counted, because "the last 60
 * sessions" is what a chart actually shows and "the last 60 days" silently
 * means ~42 of them.
 */
export function sessionWindow(
  set: BarSet,
  count: number,
  endOffset = 0,
): BarWindow {
  const n = set.calendar.length;
  const to = Math.max(0, n - 1 - endOffset);
  const from = Math.max(0, to - count + 1);
  return windowOf(set, from, to);
}

/**
 * A `count`-session window sweeping out and back across the whole set at
 * `phase` — the Gallery card's scanning motion, in **session space**.
 *
 * `scanWindow` from `src/lib/autoplay` interpolates wall-clock milliseconds,
 * which is the wrong axis here: a calendar chart collapses closed time, so a
 * window advancing at a constant ms/second visibly *stalls* over every weekend
 * and holiday. Stepping session by session moves at a constant on-screen rate.
 */
export function sessionScan(
  set: BarSet,
  count: number,
  phase: number,
): BarWindow {
  const n = set.calendar.length;
  const travel = n - count;
  if (travel <= 0) return fullWindow(set);
  const t = phase < 0.5 ? phase * 2 : (1 - phase) * 2;
  const from = Math.round(travel * t);
  return windowOf(set, from, from + count - 1);
}

/**
 * A window anchored at the **first** session whose end sweeps out and back —
 * the series drawing itself in, then scrubbing back. For a path-dependent
 * quantity (a drawdown, a cumulative return) this is the honest motion:
 * scanning a window past it would imply the value at the left edge doesn't
 * depend on everything before it. Anchoring at session 0 is also what keeps a
 * running-peak derivation correct on the cropped bars — the prefix carries its
 * whole history.
 *
 * At `phase` 0.5 the whole set is in view, which is the frame to hold for
 * reduced motion (`staticPhase: 0.5`).
 */
export function sessionReveal(
  set: BarSet,
  minCount: number,
  phase: number,
): BarWindow {
  const n = set.calendar.length;
  const t = phase < 0.5 ? phase * 2 : (1 - phase) * 2;
  const to = Math.round(minCount + (n - 1 - minCount) * t);
  return windowOf(set, 0, Math.min(n - 1, Math.max(minCount, to)));
}
