import type { ReactNode } from 'react';
import { BoundedSequence, Sequence, TimeSeries } from 'pond-ts';
import { BarChart } from './BarChart.js';
import { YAxis } from './YAxis.js';
import type { SelectInfo } from './context.js';
import {
  H,
  calendarOf,
  sessionSeq,
  weekdaySessions,
  type Session,
} from './tradingAxis.fixture.js';

/**
 * **Chart fixtures for the selection matrix** (`Interactions/Selector/*`,
 * `Interactions/MultiSelector/*`).
 *
 * The selection stories are a **matrix**: one feature set × one fixture per
 * chart type, generated by `selection-stories.tsx`. This file supplies the
 * columns; that file supplies the rows.
 *
 * **Why generated rather than hand-written per column.** A matrix is only a
 * review instrument if a difference between two columns is a difference in the
 * *library* — if each cell were written by hand, a divergence could equally be
 * someone having wired the story differently, and you'd have to read both to
 * know which. Generating every cell from one definition makes any visible
 * difference a real one. (It also makes a new chart type ~10 lines instead of a
 * dozen near-copies, which is what makes widening the matrix survivable.)
 *
 * That is not hypothetical: half a built matrix already surfaced two defects —
 * categorical hover being ink-only where the time axis claims the whole slot,
 * and `<RangeCursor>` on an ordinal axis suppressing the row's cursor entirely.
 *
 * **Capabilities are declared, not assumed.** `sequence` and `rangeCursor` are
 * absent on fixtures that cannot support them, so the factory omits those
 * stories rather than generating one that silently does nothing. A gap in the
 * matrix is information; a story that renders nothing is a trap.
 */
export interface ChartFixture {
  /** Sub-folder name in the Storybook tree (`Interactions/Selector/<name>`). */
  readonly name: string;
  /** Container props this chart needs — a `range` for a time axis. */
  readonly container: Record<string, unknown>;
  /** The primary y-axis. */
  readonly axis: { id: string; min: number; max: number; label: string };
  /** The layer under test, tagged with `id` (identity — see RFC Q8). */
  renderLayer(id: string): ReactNode;
  /** A second row's axis + layer, for the row-scoping story. */
  readonly secondary: {
    axis: { id: string; min: number; max: number; label: string };
    renderLayer(id: string): ReactNode;
  };
  /** Marks an *external* control can pick — drives the controlled-selection
   *  story, which is the case A1.2 exists to protect. */
  readonly picks: readonly { label: string; info: SelectInfo }[];
  /** How a hit reads in a caption. */
  describe(hit: SelectInfo): string;
  /** A snapping sequence, where the axis has one. Ordinal axes do not. */
  readonly sequence?: () => Sequence | BoundedSequence;
  /** Whether `<RangeCursor>` draws here — it gates on a continuous x
   *  (`brush.tsx`), so mounting one on a category axis is not just inert, it
   *  takes the row's cursor with it. */
  readonly rangeCursor: boolean;
  /**
   * Present only where the x axis **collapses closed-market time**, which is
   * what makes a snap block's relationship to the session grid a question at
   * all. Supplies the two bucketings that answer it — see the pair of stories
   * `makeSessionStories` generates.
   */
  readonly sessions?: {
    /** A bucketing that **agrees** with the session grid: one block per
     *  session, so a block's edges land exactly on the dividers. */
    conforming: () => BoundedSequence;
    /** A bucketing that **doesn't**: a wall-clock period whose boundaries fall
     *  mid-session, so a block starts inside one session, crosses the collapsed
     *  gap, and ends inside the next. */
    crossing: () => Sequence;
  };
}

const DAY = 86_400_000;
const D0 = Date.UTC(2026, 6, 1);

// ── Categorical ────────────────────────────────────────────────────────────

const SERVICES = [
  { label: 'api', value: 2.7 },
  { label: 'auth', value: 1.4 },
  { label: 'cache', value: 0.6 },
  { label: 'db', value: 3.2 },
  { label: 'queue', value: 1.05 },
  { label: 'search', value: 0.3 },
];

const ERRORS = [
  { label: 'api', value: 0.9 },
  { label: 'auth', value: 0.2 },
  { label: 'cache', value: 1.6 },
  { label: 'db', value: 0.4 },
  { label: 'queue', value: 1.1 },
  { label: 'search', value: 0.8 },
];

/** A `SelectInfo` for one category — what a legend chip / filter list hands in.
 *  On an ordinal axis the identity is the **mark** (the stable category name),
 *  not the slot index, which is the whole point of `mark` surviving a reorder. */
const svc = (label: string): SelectInfo => ({
  id: 'svc',
  key: 0,
  value: 0,
  color: '#000',
  label,
  mark: label,
});

export const categoricalBars: ChartFixture = {
  name: 'Categorical',
  container: {},
  axis: { id: 'v', min: 0, max: 3.6, label: '' },
  renderLayer: (id) => <BarChart categories={SERVICES} id={id} gap={6} />,
  secondary: {
    axis: { id: 'e', min: 0, max: 2, label: 'errors' },
    renderLayer: (id) => (
      <BarChart categories={ERRORS} id={id} gap={6} as="warn" />
    ),
  },
  picks: SERVICES.map((c) => ({ label: c.label, info: svc(c.label) })),
  describe: (hit) => hit.mark ?? hit.label,
  // No `sequence`: a time bucketing over ordinal slots is meaningless.
  // No `rangeCursor`: it gates on a continuous x.
  rangeCursor: false,
};

// ── Time axis ──────────────────────────────────────────────────────────────

/** Thirty daily interval bars — a deterministic random-ish walk. */
const daily = () =>
  new TimeSeries({
    name: 'daily',
    schema: [
      { name: 'timeRange', kind: 'timeRange' },
      { name: 'v', kind: 'number' },
    ] as const,
    rows: Array.from({ length: 30 }, (_, i) => [
      [D0 + i * DAY, D0 + (i + 1) * DAY],
      6 + 4 * Math.sin(i / 3) + 1.5 * Math.sin(i * 1.7),
    ]) as [[number, number], number][],
  });

/** A second daily series for the row-scoping story. */
const dailyErrors = () =>
  new TimeSeries({
    name: 'errs',
    schema: [
      { name: 'timeRange', kind: 'timeRange' },
      { name: 'v', kind: 'number' },
    ] as const,
    rows: Array.from({ length: 30 }, (_, i) => [
      [D0 + i * DAY, D0 + (i + 1) * DAY],
      1 + Math.abs(Math.sin(i * 0.9)) * 1.4,
    ]) as [[number, number], number][],
  });

const isoDay = (t: number) => new Date(t).toISOString().slice(5, 10);

export const timeBars: ChartFixture = {
  name: 'BarChart',
  container: { range: [D0, D0 + 30 * DAY] },
  axis: { id: 'v', min: 0, max: 12, label: '' },
  renderLayer: (id) => (
    <BarChart series={daily()} column="v" axis="v" id={id} />
  ),
  secondary: {
    axis: { id: 'e', min: 0, max: 3, label: 'errors' },
    renderLayer: (id) => (
      <BarChart series={dailyErrors()} column="v" axis="e" id={id} as="warn" />
    ),
  },
  // A time hit's identity is its `key` (the bar's begin), so an external
  // control picks by timestamp rather than by name.
  picks: [0, 4, 9].map((i) => ({
    label: isoDay(D0 + i * DAY),
    info: {
      id: 'svc',
      key: D0 + i * DAY,
      value: 0,
      color: '#000',
      label: 'v',
    },
  })),
  describe: (hit) => isoDay(hit.key),
  /**
   * **The bucket must be coarser than the bar**, or the snap has nothing to do
   * and the story silently demonstrates nothing: these are *daily* bars, so a
   * `'1d'` sequence would bucket exactly one bar each and look identical to the
   * freeform sweep. A week spans seven, which is visible. Anchored at the first
   * bar so the buckets line up with the data rather than with the epoch.
   */
  sequence: () => Sequence.every('7d', { anchor: D0 }),
  rangeCursor: true,
};

// ── Stacked bars (many marks per bin) ──────────────────────────────────────

/** The stack's groups, bottom → top. **Four**, so the story walks the whole
 *  `defaultTheme` group ramp rather than the first few entries of it. */
const TIERS = ['web', 'api', 'db', 'edge'] as const;

/** Twenty daily bins, four positive segments each. */
const stacked = () =>
  new TimeSeries({
    name: 'tiers',
    schema: [
      { name: 'timeRange', kind: 'timeRange' },
      { name: 'web', kind: 'number' },
      { name: 'api', kind: 'number' },
      { name: 'db', kind: 'number' },
      { name: 'edge', kind: 'number' },
    ] as const,
    rows: Array.from({ length: 20 }, (_, i) => [
      [D0 + i * DAY, D0 + (i + 1) * DAY],
      3 + 2 * Math.sin(i / 2),
      2 + 1.5 * Math.sin(i / 3 + 1),
      1.5 + Math.sin(i * 1.7),
      1.2 + Math.sin(i / 4 + 2),
    ]) as [[number, number], number, number, number, number][],
  });

/**
 * **A stacked bar chart** — the column where a bin holds *many* marks.
 *
 * Every other column is one mark per x position, so "the mark under the
 * pointer" and "the bin under the pointer" are the same thing and nothing
 * distinguishes them. Here they come apart: a wide series carries no stable
 * per-bin `mark`, so a segment's identity is the pair **`(key = bin begin,
 * label = group)`** and one bin's three segments share a key. That is the
 * axis this column exercises — click resolves to a segment, while a sweep
 * materialises *every* drawn segment of every covered bin.
 */
export const stackedBars: ChartFixture = {
  name: 'Stacked',
  container: { range: [D0, D0 + 20 * DAY] },
  axis: { id: 'v', min: 0, max: 14, label: '' },
  renderLayer: (id) => (
    <BarChart series={stacked()} columns={TIERS} axis="v" id={id} />
  ),
  secondary: {
    axis: { id: 'e', min: 0, max: 3, label: 'errors' },
    renderLayer: (id) => (
      <BarChart series={dailyErrors()} column="v" axis="e" id={id} as="warn" />
    ),
  },
  // A segment is picked by `(key, label)` — `stackIndexMatches` falls to
  // `labelsByKey` when the series carries no stable marks, so an external
  // control naming only the day would match nothing.
  picks: [
    { day: 0, tier: 'web' },
    { day: 4, tier: 'api' },
    { day: 9, tier: 'db' },
  ].map(({ day, tier }) => ({
    label: `${isoDay(D0 + day * DAY)}·${tier}`,
    info: {
      id: 'svc',
      key: D0 + day * DAY,
      value: 0,
      color: '#000',
      label: tier,
    },
  })),
  /** `describeEntries` renders a span's endpoints through this with a
   *  `{ key }`-only cast, so a missing label is a real case here rather than
   *  defensive noise — a span names an x range, not a group. */
  describe: (hit) =>
    hit.label === undefined
      ? isoDay(hit.key)
      : `${isoDay(hit.key)}·${hit.label}`,
  sequence: () => Sequence.every('7d', { anchor: D0 }),
  rangeCursor: true,
};

// ── Trading sessions (a discontinuous time axis) ───────────────────────────

/** Six weekday sessions (09:30–16:00 UTC) from a Monday — five overnight seams
 *  plus a **weekend** one, which is the widest collapse in view. */
const SESSIONS: Session[] = weekdaySessions(6);
const MON_OPEN = SESSIONS[0]!.open;

/** Hourly interval bars inside each session, the last one clipped at the close.
 *  Seven bars per session (09:30 … 15:30), so a block is countable by eye. */
const sessionBars = (amp: number, phase: number) => {
  const rows: [[number, number], number][] = [];
  let i = 0;
  for (const s of SESSIONS) {
    for (let t = s.open; t < s.close; t += H, i++) {
      rows.push([
        [t, Math.min(t + H, s.close)],
        6 + amp * Math.sin(i / 3 + phase) + 1.2 * Math.sin(i * 1.7),
      ]);
    }
  }
  return new TimeSeries({
    name: 'session',
    schema: [
      { name: 'timeRange', kind: 'timeRange' },
      { name: 'v', kind: 'number' },
    ] as const,
    rows,
  });
};

const stamp = (t: number) =>
  new Date(t).toISOString().slice(5, 16).replace('T', ' ');

/**
 * **A trading-time axis** — closed-market time collapsed, session dividers
 * drawn. Selection on a *continuous* axis never has to ask where a block's
 * edges fall relative to the data's own structure; here it does, because the
 * axis has seams and a wall-clock bucketing knows nothing about them.
 *
 * `sessionDividers: 'all'` is part of the fixture rather than of one story:
 * every cell in this column is about the session grid, so the grid should be
 * visible in all of them.
 */
export const tradingSessions: ChartFixture = {
  name: 'TradingSessions',
  container: {
    /**
     * Wider than the other columns — 42 bars across 6 sessions.
     *
     * **The x labels still crowd, and that is a defect this column found.**
     * The trading axis budgets `TRADING_TICK_PX` (65px) of plot per tick and
     * picks the finest grain that fits; here that is 12 hours. But a `00:00`
     * anchor is not *inside* any session, so the collapse relocates it to the
     * session open (09:30) — 2.5h into a 6.5h session, ~33px from that
     * session's `12:00` label. The budget bounds spacing in wall-clock time
     * and the axis draws in trading time, so it does not bound what it thinks
     * it bounds. Widening moves the labels from overlapping to merely
     * abutting, which is why 820 rather than the shared 640.
     *
     * Left visible on purpose: it is orthogonal to selection, and papering
     * over it (fewer sessions, one bar per session) would cost the weekend
     * seam the crossing story is built on.
     */
    width: 820,
    range: [MON_OPEN, SESSIONS[SESSIONS.length - 1]!.close],
    // The high-level sugar; the container derives the provider itself. Built
    // once at module scope because the prop must be a *stable* reference.
    calendar: calendarOf(SESSIONS),
    sessionDividers: 'all',
  },
  axis: { id: 'v', min: 0, max: 12, label: '' },
  renderLayer: (id) => (
    <BarChart series={sessionBars(4, 0)} column="v" axis="v" id={id} />
  ),
  secondary: {
    axis: { id: 'e', min: 0, max: 12, label: 'errors' },
    renderLayer: (id) => (
      <BarChart
        series={sessionBars(2.2, 1.1)}
        column="v"
        axis="e"
        id={id}
        as="warn"
      />
    ),
  },
  picks: [0, 3, 8].map((i) => ({
    label: stamp(MON_OPEN + i * H),
    info: {
      id: 'svc',
      key: MON_OPEN + i * H,
      value: 0,
      color: '#000',
      label: 'v',
    },
  })),
  describe: (hit) => stamp(hit.key),
  // The column's ordinary `SweepWithSequence` cell snaps to whole sessions —
  // the same bucketing `sessions.conforming` names, so the generated story and
  // the session pair below agree about what "conforming" means.
  sequence: () => sessionSeq(SESSIONS),
  rangeCursor: true,
  sessions: {
    conforming: () => sessionSeq(SESSIONS),
    /**
     * **Noon-thirty to noon-thirty.** A wall-clock day bucket anchored inside
     * the session, so no boundary can coincide with an open or a close: every
     * block takes the afternoon of one session and the morning of the next.
     * 12:30 is deliberately a *bar* edge — the block straddling a seam is the
     * subject, and a bucket boundary bisecting a bar would be a second,
     * unrelated question.
     */
    crossing: () => Sequence.every('1d', { anchor: MON_OPEN + 3 * H }),
  },
};

/** Every column of the matrix, in tree order. */
export const FIXTURES = [
  categoricalBars,
  timeBars,
  stackedBars,
  tradingSessions,
] as const;

/** Shared caption styling, so every cell reads identically. */
export const caption = {
  font: '13px system-ui',
  color: '#667',
  marginTop: 4,
  maxWidth: 640,
} as const;

export { DAY, D0 };
