import type { ReactNode } from 'react';
import { BoundedSequence, Sequence, TimeSeries } from 'pond-ts';
import { BarChart } from './BarChart.js';
import { BoxPlot } from './BoxPlot.js';
import { Candlestick } from './Candlestick.js';
import { HeatMap } from './HeatMap.js';
import { ScatterChart } from './ScatterChart.js';
import { YAxis } from './YAxis.js';
import type { SelectInfo } from './context.js';
import {
  H,
  calendarOf,
  sessionSeq,
  weekdaySessions,
  type Session,
} from './tradingAxis.fixture.js';

/**
 * **Chart fixtures for the selection matrix** (`Interactions/Selector/*`,
 * `Interactions/MultiSelector/*`).
 *
 * The selection stories are a **matrix**: one feature set × one fixture per
 * chart type, generated by `selection-stories.tsx`. This file supplies the
 * columns; that file supplies the rows.
 *
 * **Why generated rather than hand-written per column.** A matrix is only a
 * review instrument if a difference between two columns is a difference in the
 * *library* — if each cell were written by hand, a divergence could equally be
 * someone having wired the story differently, and you'd have to read both to
 * know which. Generating every cell from one definition makes any visible
 * difference a real one. (It also makes a new chart type ~10 lines instead of a
 * dozen near-copies, which is what makes widening the matrix survivable.)
 *
 * That is not hypothetical: half a built matrix already surfaced two defects —
 * categorical hover being ink-only where the time axis claims the whole slot,
 * and `<RangeCursor>` on an ordinal axis suppressing the row's cursor entirely.
 *
 * **Capabilities are declared, not assumed.** `sequence` and `rangeCursor` are
 * absent on fixtures that cannot support them, so the factory omits those
 * stories rather than generating one that silently does nothing. A gap in the
 * matrix is information; a story that renders nothing is a trap.
 */
export interface ChartFixture {
  /** Sub-folder name in the Storybook tree (`Interactions/Selector/<name>`). */
  readonly name: string;
  /** Container props this chart needs — a `range` for a time axis. */
  readonly container: Record<string, unknown>;
  /** The primary y-axis. */
  readonly axis: { id: string; min: number; max: number; label: string };
  /** The layer under test, tagged with `id` (identity — see RFC Q8). */
  renderLayer(id: string): ReactNode;
  /** A second row's axis + layer, for the row-scoping story. */
  readonly secondary: {
    axis: { id: string; min: number; max: number; label: string };
    renderLayer(id: string): ReactNode;
  };
  /** Marks an *external* control can pick — drives the controlled-selection
   *  story, the case `<Selector enabled={false}>` exists to protect. */
  readonly picks: readonly { label: string; info: SelectInfo }[];
  /** How a hit reads in a caption. */
  describe(hit: SelectInfo): string;
  /**
   * Whether the layer publishes `beginSweep` — i.e. whether it can be
   * **swept at all**. Without one a mounted `<MultiSelector>` has neither a
   * drag nor a resting block preview, so every cell of that column would
   * render a chart that quietly ignores the component under test.
   *
   * `false` on the **2-D family** — scatter and heat map — whose marks do not
   * reduce to a run of columns, so the gesture they need is
   * [PND-INTERACT2D]'s rect rather than this one on a new layer. The list
   * family still owes the sweep too ([PND-INTERACTCONF]).
   */
  readonly sweep: boolean;
  /** A snapping sequence, where the axis has one. Ordinal axes do not. */
  readonly sequence?: () => Sequence | BoundedSequence;
  /** Whether `<RangeCursor>` draws here — it gates on a continuous x
   *  (`brush.tsx`), so mounting one on a category axis is not just inert, it
   *  takes the row's cursor with it. */
  readonly rangeCursor: boolean;
  /**
   * Present only where the x axis **collapses closed-market time**, which is
   * what makes a snap block's relationship to the session grid a question at
   * all. Supplies the two bucketings that answer it — see the pair of stories
   * `makeSessionStories` generates.
   */
  readonly sessions?: {
    /** A bucketing that **agrees** with the session grid: one block per
     *  session, so a block's edges land exactly on the dividers. */
    conforming: () => BoundedSequence;
    /** A bucketing that **doesn't**: a wall-clock period whose boundaries fall
     *  mid-session, so a block starts inside one session, crosses the collapsed
     *  gap, and ends inside the next. */
    crossing: () => Sequence;
  };
}

const DAY = 86_400_000;
const D0 = Date.UTC(2026, 6, 1);

// ── Categorical ────────────────────────────────────────────────────────────

const SERVICES = [
  { label: 'api', value: 2.7 },
  { label: 'auth', value: 1.4 },
  { label: 'cache', value: 0.6 },
  { label: 'db', value: 3.2 },
  { label: 'queue', value: 1.05 },
  { label: 'search', value: 0.3 },
];

const ERRORS = [
  { label: 'api', value: 0.9 },
  { label: 'auth', value: 0.2 },
  { label: 'cache', value: 1.6 },
  { label: 'db', value: 0.4 },
  { label: 'queue', value: 1.1 },
  { label: 'search', value: 0.8 },
];

/** A `SelectInfo` for one category — what a legend chip / filter list hands in.
 *  On an ordinal axis the identity is the **mark** (the stable category name),
 *  not the slot index, which is the whole point of `mark` surviving a reorder. */
const svc = (label: string): SelectInfo => ({
  id: 'svc',
  key: 0,
  value: 0,
  color: '#000',
  label,
  mark: label,
});

export const categoricalBars: ChartFixture = {
  name: 'Categorical',
  container: {},
  axis: { id: 'v', min: 0, max: 3.6, label: '' },
  renderLayer: (id) => <BarChart categories={SERVICES} id={id} gap={6} />,
  secondary: {
    axis: { id: 'e', min: 0, max: 2, label: 'errors' },
    renderLayer: (id) => (
      <BarChart categories={ERRORS} id={id} gap={6} as="warn" />
    ),
  },
  picks: SERVICES.map((c) => ({ label: c.label, info: svc(c.label) })),
  describe: (hit) => hit.mark ?? hit.label,
  // No `sequence`: a time bucketing over ordinal slots is meaningless.
  // No `rangeCursor`: it gates on a continuous x.
  rangeCursor: false,
  sweep: true,
};

// ── Time axis ──────────────────────────────────────────────────────────────

/** Thirty daily interval bars — a deterministic random-ish walk. */
const daily = () =>
  new TimeSeries({
    name: 'daily',
    schema: [
      { name: 'timeRange', kind: 'timeRange' },
      { name: 'v', kind: 'number' },
    ] as const,
    rows: Array.from({ length: 30 }, (_, i) => [
      [D0 + i * DAY, D0 + (i + 1) * DAY],
      6 + 4 * Math.sin(i / 3) + 1.5 * Math.sin(i * 1.7),
    ]) as [[number, number], number][],
  });

/** A second daily series for the row-scoping story. */
const dailyErrors = () =>
  new TimeSeries({
    name: 'errs',
    schema: [
      { name: 'timeRange', kind: 'timeRange' },
      { name: 'v', kind: 'number' },
    ] as const,
    rows: Array.from({ length: 30 }, (_, i) => [
      [D0 + i * DAY, D0 + (i + 1) * DAY],
      1 + Math.abs(Math.sin(i * 0.9)) * 1.4,
    ]) as [[number, number], number][],
  });

const isoDay = (t: number) => new Date(t).toISOString().slice(5, 10);

export const timeBars: ChartFixture = {
  name: 'BarChart',
  container: { range: [D0, D0 + 30 * DAY] },
  axis: { id: 'v', min: 0, max: 12, label: '' },
  renderLayer: (id) => (
    <BarChart series={daily()} column="v" axis="v" id={id} />
  ),
  secondary: {
    axis: { id: 'e', min: 0, max: 3, label: 'errors' },
    renderLayer: (id) => (
      <BarChart series={dailyErrors()} column="v" axis="e" id={id} as="warn" />
    ),
  },
  // A time hit's identity is its `key` (the bar's begin), so an external
  // control picks by timestamp rather than by name.
  picks: [0, 4, 9].map((i) => ({
    label: isoDay(D0 + i * DAY),
    info: {
      id: 'svc',
      key: D0 + i * DAY,
      value: 0,
      color: '#000',
      label: 'v',
    },
  })),
  describe: (hit) => isoDay(hit.key),
  /**
   * **The bucket must be coarser than the bar**, or the snap has nothing to do
   * and the story silently demonstrates nothing: these are *daily* bars, so a
   * `'1d'` sequence would bucket exactly one bar each and look identical to the
   * freeform sweep. A week spans seven, which is visible. Anchored at the first
   * bar so the buckets line up with the data rather than with the epoch.
   */
  sequence: () => Sequence.every('7d', { anchor: D0 }),
  rangeCursor: true,
  sweep: true,
};

// ── Stacked bars (many marks per bin) ──────────────────────────────────────

/** The stack's groups, bottom → top. **Four**, so the story walks the whole
 *  `defaultTheme` group ramp rather than the first few entries of it. */
const TIERS = ['web', 'api', 'db', 'edge'] as const;

/** Twenty daily bins, four positive segments each. */
const stacked = () =>
  new TimeSeries({
    name: 'tiers',
    schema: [
      { name: 'timeRange', kind: 'timeRange' },
      { name: 'web', kind: 'number' },
      { name: 'api', kind: 'number' },
      { name: 'db', kind: 'number' },
      { name: 'edge', kind: 'number' },
    ] as const,
    rows: Array.from({ length: 20 }, (_, i) => [
      [D0 + i * DAY, D0 + (i + 1) * DAY],
      3 + 2 * Math.sin(i / 2),
      2 + 1.5 * Math.sin(i / 3 + 1),
      1.5 + Math.sin(i * 1.7),
      1.2 + Math.sin(i / 4 + 2),
    ]) as [[number, number], number, number, number, number][],
  });

/**
 * **A stacked bar chart** — the column where a bin holds *many* marks.
 *
 * Every other column is one mark per x position, so "the mark under the
 * pointer" and "the bin under the pointer" are the same thing and nothing
 * distinguishes them. Here they come apart: a wide series carries no stable
 * per-bin `mark`, so a segment's identity is the pair **`(key = bin begin,
 * label = group)`** and one bin's three segments share a key. That is the
 * axis this column exercises — click resolves to a segment, while a sweep
 * materialises *every* drawn segment of every covered bin.
 */
export const stackedBars: ChartFixture = {
  name: 'Stacked',
  container: { range: [D0, D0 + 20 * DAY] },
  axis: { id: 'v', min: 0, max: 14, label: '' },
  renderLayer: (id) => (
    <BarChart series={stacked()} columns={TIERS} axis="v" id={id} />
  ),
  secondary: {
    axis: { id: 'e', min: 0, max: 3, label: 'errors' },
    renderLayer: (id) => (
      <BarChart series={dailyErrors()} column="v" axis="e" id={id} as="warn" />
    ),
  },
  // A segment is picked by `(key, label)` — `stackIndexMatches` falls to
  // `labelsByKey` when the series carries no stable marks, so an external
  // control naming only the day would match nothing.
  picks: [
    { day: 0, tier: 'web' },
    { day: 4, tier: 'api' },
    { day: 9, tier: 'db' },
  ].map(({ day, tier }) => ({
    label: `${isoDay(D0 + day * DAY)}·${tier}`,
    info: {
      id: 'svc',
      key: D0 + day * DAY,
      value: 0,
      color: '#000',
      label: tier,
    },
  })),
  /** `describeEntries` renders a span's endpoints through this with a
   *  `{ key }`-only cast, so a missing label is a real case here rather than
   *  defensive noise — a span names an x range, not a group. */
  describe: (hit) =>
    hit.label === undefined
      ? isoDay(hit.key)
      : `${isoDay(hit.key)}·${hit.label}`,
  sequence: () => Sequence.every('7d', { anchor: D0 }),
  rangeCursor: true,
  sweep: true,
};

// ── Box plots (a mark with internal structure) ─────────────────────────────

const BOX_BASE = Date.UTC(2026, 6, 1, 12, 0, 0);
const BOX_BUCKET = 600_000; // 10 minutes
const BOX_COUNT = 10;

/**
 * Ten percentile buckets through pond's own `aggregate` — the reducers do the
 * quantiles, the fixture just reads the columns (the idiom `Box.stories.tsx`
 * established). Deterministic samples, so the boxes are stable across runs.
 */
const boxes = (phase = 0) => {
  const STEP = 5_000; // one raw sample / 5s
  const N = (BOX_COUNT * BOX_BUCKET) / STEP;
  const rows: [number, number][] = Array.from({ length: N }, (_, i) => [
    BOX_BASE + i * STEP,
    60 +
      18 * Math.sin(i / 70 + phase) +
      9 * Math.sin(i * 1.3) +
      5 * Math.sin(i * 2.7) +
      3 * Math.sin(i * 0.7),
  ]);
  return new TimeSeries({
    name: 'raw',
    schema: [
      { name: 'time', kind: 'time' },
      { name: 'latency', kind: 'number' },
    ] as const,
    rows,
  }).aggregate(Sequence.every('10m'), {
    p5: { from: 'latency', using: 'p5' },
    p25: { from: 'latency', using: 'p25' },
    p50: { from: 'latency', using: 'p50' },
    p75: { from: 'latency', using: 'p75' },
    p95: { from: 'latency', using: 'p95' },
  });
};

/** **Local** time, because the axis renders local — a UTC caption beside a
 *  local axis reads as an off-by-hours bug in the hit test, which is exactly
 *  the kind of false lead a review story must not plant. */
const clock = (t: number) => new Date(t).toTimeString().slice(0, 5);

/**
 * **A box plot column** — the first fixture whose mark has *internal
 * structure*. Everything before it is one filled rect per x; a box is a body,
 * a median rule and (depending on `shape`) stems and caps, and `hitTest` is
 * rect containment over that composite. So the question this column asks is
 * **what counts as the mark for hit purposes**, and the answer is allowed to
 * differ by shape — which is why it ships as two columns rather than one.
 *
 * It sweeps like any bar column. A box is an **aggregation** — it owns one
 * `[begin, end)` interval of the key axis — so the fact that its ink floats
 * between two quantiles instead of rising from the baseline says nothing about
 * which column the mark occupies. The sweep cuts columns, not ink.
 */
const boxFixture = (
  name: string,
  shape: 'whisker' | 'solid',
  note: string,
): ChartFixture => ({
  name,
  container: { range: [BOX_BASE, BOX_BASE + BOX_COUNT * BOX_BUCKET] },
  axis: { id: 'v', min: 0, max: 110, label: note },
  renderLayer: (id) => (
    <BoxPlot
      series={boxes()}
      lower="p5"
      q1="p25"
      median="p50"
      q3="p75"
      upper="p95"
      axis="v"
      shape={shape}
      gap={10}
      id={id}
    />
  ),
  secondary: {
    axis: { id: 'e', min: 0, max: 110, label: 'p95 (b)' },
    renderLayer: (id) => (
      <BoxPlot
        series={boxes(2.1)}
        lower="p5"
        q1="p25"
        median="p50"
        q3="p75"
        upper="p95"
        axis="e"
        shape={shape}
        gap={10}
        as="warn"
        id={id}
      />
    ),
  },
  // A box's `key` is its `x` (the bucket begin), same identity rule the
  // time-axis bar column uses.
  picks: [0, 3, 7].map((i) => ({
    label: clock(BOX_BASE + i * BOX_BUCKET),
    info: {
      id: 'svc',
      key: BOX_BASE + i * BOX_BUCKET,
      value: 0,
      color: '#000',
      label: 'latency',
    },
  })),
  describe: (hit) => clock(hit.key),
  sweep: true,
  /** Three 10-minute boxes per bucket — coarser than the mark, so the snap has
   *  something to do (the lesson `timeBars` learned with its `'1d'`). */
  sequence: () => Sequence.every('30m', { anchor: BOX_BASE }),
  rangeCursor: true,
});

/** The default shape: a q1→q3 body with thin stems and end caps. The stems are
 *  the interesting part for selection — they are drawn ink far from the body. */
export const boxWhisker: ChartFixture = boxFixture(
  'BoxWhisker',
  'whisker',
  'whisker',
);

/** The candlestick look: a light outer bar over the full range, a darker inner
 *  body, no stems. The mark is one solid rect, so the hittable area is the
 *  whole p5→p95 span rather than a body plus two thin stems. */
export const boxSolid: ChartFixture = boxFixture('BoxSolid', 'solid', 'solid');

// ── Candlesticks (a mark whose HUE is its meaning) ─────────────────────────

/** Twenty daily OHLC bars, deterministic, with real direction changes so both
 *  the rising and falling colours are on screen in every state. */
const ohlc = () => {
  const rows: [number, number, number, number, number][] = [];
  let px = 100;
  for (let i = 0; i < 20; i += 1) {
    const drift = 2.2 * Math.sin(i / 2.4) + 1.1 * Math.sin(i * 1.7);
    const open = px;
    const close = px + drift;
    const wick = 0.8 + Math.abs(Math.sin(i * 2.3));
    rows.push([
      D0 + i * DAY,
      open,
      Math.max(open, close) + wick,
      Math.min(open, close) - wick,
      close,
    ]);
    px = close;
  }
  return new TimeSeries({
    name: 'ohlc',
    schema: [
      { name: 'time', kind: 'time' },
      { name: 'open', kind: 'number' },
      { name: 'high', kind: 'number' },
      { name: 'low', kind: 'number' },
      { name: 'close', kind: 'number' },
    ] as const,
    rows,
  });
};

/**
 * **A candlestick column** — the mark whose *hue is its meaning*.
 *
 * Every other column is free to recolour on selection: a bar swaps its fill, a
 * box rotates its whole tint ladder. A candle cannot. Rising vs falling is the
 * first thing anyone reads off it, and that read lives in exactly the channel
 * the other marks use to announce state — so this column exists to check that
 * a selected candle still says which way the price went.
 *
 * It sweeps like the rest: a candle owns one `[x, xEnd)` column, same as a box.
 */
export const candles: ChartFixture = {
  name: 'Candlestick',
  container: { range: [D0, D0 + 20 * DAY] },
  axis: { id: 'v', min: 88, max: 116, label: '' },
  renderLayer: (id) => <Candlestick series={ohlc()} axis="v" gap={6} id={id} />,
  secondary: {
    axis: { id: 'e', min: 88, max: 116, label: 'bar' },
    renderLayer: (id) => (
      <Candlestick series={ohlc()} axis="e" gap={6} variant="bar" id={id} />
    ),
  },
  picks: [0, 5, 11].map((i) => ({
    label: isoDay(D0 + i * DAY),
    info: {
      id: 'svc',
      key: D0 + i * DAY,
      value: 0,
      color: '#000',
      label: 'close',
    },
  })),
  describe: (hit) => isoDay(hit.key),
  sweep: true,
  sequence: () => Sequence.every('5d', { anchor: D0 }),
  rangeCursor: true,
};

// ── The 2-D family: scatter and heat map ──────────────────────────────────

/** Forty points on a time axis — a scatter's marks live at `(x, y)`, not in a
 *  column, which is the whole distinction this pair of columns exists to make. */
const points = () =>
  new TimeSeries({
    name: 'pts',
    schema: [
      { name: 'time', kind: 'time' },
      { name: 'v', kind: 'number' },
      { name: 'w', kind: 'number' },
    ] as const,
    rows: Array.from({ length: 40 }, (_, i) => [
      D0 + i * (DAY / 2),
      6 + 3.4 * Math.sin(i / 3.1) + 1.8 * Math.sin(i * 2.3),
      1 + Math.abs(Math.sin(i * 1.7)),
    ]) as [number, number, number][],
  });

/** Three rows × twenty daily bins — a grid of cells. */
const grid = () =>
  new TimeSeries({
    name: 'grid',
    schema: [
      { name: 'timeRange', kind: 'timeRange' },
      { name: 'low', kind: 'number' },
      { name: 'mid', kind: 'number' },
      { name: 'high', kind: 'number' },
    ] as const,
    rows: Array.from({ length: 20 }, (_, i) => [
      [D0 + i * DAY, D0 + (i + 1) * DAY],
      2 + 2 * Math.sin(i / 2.2),
      5 + 3 * Math.sin(i / 3.3 + 1),
      8 + 3 * Math.sin(i / 1.9 + 2),
    ]) as [[number, number], number, number, number][],
  });

const HEAT_RAMP = ['#e0f2f1', '#7FC8BF', '#2A9D8F', '#1F7A6F'];

/**
 * **A scatter column** — the first mark that does *not* own a column.
 *
 * Every fixture before this one is an interval on the key axis: a bar, a
 * stacked bin, a box, a candle. A scatter point is a position, `(x, y)`, with
 * no span either side of it — so "the marks between here and there" is a
 * question about a **region**, not about a run of columns, and `sweep1D`'s
 * two binary searches have nothing to cut.
 *
 * Hence `sweep: false`, and hence [PND-INTERACT2D] rather than a quick wiring
 * job: the 2-D rect is a different gesture, not the same one on a new layer.
 */
export const scatterPoints: ChartFixture = {
  name: 'Scatter',
  container: { range: [D0, D0 + 20 * DAY] },
  axis: { id: 'v', min: 0, max: 12, label: '' },
  renderLayer: (id) => (
    <ScatterChart series={points()} column="v" axis="v" id={id} />
  ),
  secondary: {
    axis: { id: 'e', min: 0, max: 3, label: 'w' },
    renderLayer: (id) => (
      <ScatterChart series={points()} column="w" axis="e" id={id} as="warn" />
    ),
  },
  picks: [0, 8, 17].map((i) => ({
    label: isoDay(D0 + i * (DAY / 2)),
    info: {
      id: 'svc',
      key: D0 + i * (DAY / 2),
      value: 0,
      color: '#000',
      label: 'v',
    },
  })),
  describe: (hit) => isoDay(hit.key),
  // A **2-D** sweep: the drag cuts a free rect, and the committed span carries
  // a `y` window alongside `x` ([PND-INTERACT2D]).
  sweep: true,
  rangeCursor: true,
};

/**
 * **A heat-map column** — a *grid* of cells, `(bin × row)`.
 *
 * A heat map's bins do own columns, so an x-only sweep would be well defined —
 * and it would also be the wrong gesture. Selecting every row of a covered bin
 * ignores the y dimension the mark exists to show, and the rect that reads it
 * is [PND-INTERACT2D]'s, so this declares `sweep: false` rather than shipping
 * the half of the gesture that happens to be easy.
 */
export const heatGrid: ChartFixture = {
  name: 'HeatMap',
  container: { range: [D0, D0 + 20 * DAY] },
  axis: { id: 'v', min: 0, max: 3, label: '' },
  renderLayer: (id) => (
    <HeatMap
      series={grid()}
      columns={['low', 'mid', 'high']}
      colors={HEAT_RAMP}
      axis="v"
      id={id}
    />
  ),
  secondary: {
    axis: { id: 'e', min: 0, max: 3, label: 'again' },
    renderLayer: (id) => (
      <HeatMap
        series={grid()}
        columns={['low', 'mid', 'high']}
        colors={HEAT_RAMP}
        axis="e"
        id={id}
      />
    ),
  },
  // A cell's identity is `(key = bin begin, label = row)`, the stack's rule.
  picks: [
    { day: 2, row: 'low' },
    { day: 7, row: 'mid' },
    { day: 13, row: 'high' },
  ].map(({ day, row }) => ({
    label: `${isoDay(D0 + day * DAY)}·${row}`,
    info: {
      id: 'svc',
      key: D0 + day * DAY,
      value: 0,
      color: '#000',
      label: row,
    },
  })),
  describe: (hit) =>
    hit.label === undefined
      ? isoDay(hit.key)
      : `${isoDay(hit.key)}·${hit.label}`,
  // A **2-D** sweep, snapped in both dimensions — bins on x, rows on y — so a
  // capture is always a contiguous rectangle of cells ([PND-INTERACT2D]).
  sweep: true,
  rangeCursor: true,
};

// ── Trading sessions (a discontinuous time axis) ───────────────────────────

/** Six weekday sessions (09:30–16:00 UTC) from a Monday — five overnight seams
 *  plus a **weekend** one, which is the widest collapse in view. */
const SESSIONS: Session[] = weekdaySessions(6);
const MON_OPEN = SESSIONS[0]!.open;

/** Hourly interval bars inside each session, the last one clipped at the close.
 *  Seven bars per session (09:30 … 15:30), so a block is countable by eye. */
const sessionBars = (amp: number, phase: number) => {
  const rows: [[number, number], number][] = [];
  let i = 0;
  for (const s of SESSIONS) {
    for (let t = s.open; t < s.close; t += H, i++) {
      rows.push([
        [t, Math.min(t + H, s.close)],
        6 + amp * Math.sin(i / 3 + phase) + 1.2 * Math.sin(i * 1.7),
      ]);
    }
  }
  return new TimeSeries({
    name: 'session',
    schema: [
      { name: 'timeRange', kind: 'timeRange' },
      { name: 'v', kind: 'number' },
    ] as const,
    rows,
  });
};

const stamp = (t: number) =>
  new Date(t).toISOString().slice(5, 16).replace('T', ' ');

/**
 * **A trading-time axis** — closed-market time collapsed, session dividers
 * drawn. Selection on a *continuous* axis never has to ask where a block's
 * edges fall relative to the data's own structure; here it does, because the
 * axis has seams and a wall-clock bucketing knows nothing about them.
 *
 * `sessionDividers: 'all'` is part of the fixture rather than of one story:
 * every cell in this column is about the session grid, so the grid should be
 * visible in all of them.
 */
export const tradingSessions: ChartFixture = {
  name: 'TradingSessions',
  container: {
    /**
     * Wider than the other columns — 42 bars across 6 sessions.
     *
     * **The x labels still crowd, and that is a defect this column found.**
     * The trading axis budgets `TRADING_TICK_PX` (65px) of plot per tick and
     * picks the finest grain that fits; here that is 12 hours. But a `00:00`
     * anchor is not *inside* any session, so the collapse relocates it to the
     * session open (09:30) — 2.5h into a 6.5h session, ~33px from that
     * session's `12:00` label. The budget bounds spacing in wall-clock time
     * and the axis draws in trading time, so it does not bound what it thinks
     * it bounds. Widening moves the labels from overlapping to merely
     * abutting, which is why 820 rather than the shared 640.
     *
     * Left visible on purpose: it is orthogonal to selection, and papering
     * over it (fewer sessions, one bar per session) would cost the weekend
     * seam the crossing story is built on.
     */
    width: 820,
    range: [MON_OPEN, SESSIONS[SESSIONS.length - 1]!.close],
    // The high-level sugar; the container derives the provider itself. Built
    // once at module scope because the prop must be a *stable* reference.
    calendar: calendarOf(SESSIONS),
    sessionDividers: 'all',
  },
  axis: { id: 'v', min: 0, max: 12, label: '' },
  renderLayer: (id) => (
    <BarChart series={sessionBars(4, 0)} column="v" axis="v" id={id} />
  ),
  secondary: {
    axis: { id: 'e', min: 0, max: 12, label: 'errors' },
    renderLayer: (id) => (
      <BarChart
        series={sessionBars(2.2, 1.1)}
        column="v"
        axis="e"
        id={id}
        as="warn"
      />
    ),
  },
  picks: [0, 3, 8].map((i) => ({
    label: stamp(MON_OPEN + i * H),
    info: {
      id: 'svc',
      key: MON_OPEN + i * H,
      value: 0,
      color: '#000',
      label: 'v',
    },
  })),
  describe: (hit) => stamp(hit.key),
  // The column's ordinary `SweepWithSequence` cell snaps to whole sessions —
  // the same bucketing `sessions.conforming` names, so the generated story and
  // the session pair below agree about what "conforming" means.
  sequence: () => sessionSeq(SESSIONS),
  rangeCursor: true,
  sweep: true,
  sessions: {
    conforming: () => sessionSeq(SESSIONS),
    /**
     * **Noon-thirty to noon-thirty.** A wall-clock day bucket anchored inside
     * the session, so no boundary can coincide with an open or a close: every
     * block takes the afternoon of one session and the morning of the next.
     * 12:30 is deliberately a *bar* edge — the block straddling a seam is the
     * subject, and a bucket boundary bisecting a bar would be a second,
     * unrelated question.
     */
    crossing: () => Sequence.every('1d', { anchor: MON_OPEN + 3 * H }),
  },
};

/** Every column of the matrix, in tree order. */
export const FIXTURES = [
  categoricalBars,
  timeBars,
  stackedBars,
  boxWhisker,
  boxSolid,
  candles,
  scatterPoints,
  heatGrid,
  tradingSessions,
] as const;

/** Shared caption styling, so every cell reads identically. */
export const caption = {
  font: '13px system-ui',
  color: '#667',
  marginTop: 4,
  maxWidth: 640,
} as const;

export { DAY, D0 };
