import type { ReactNode } from 'react';
import { Sequence, TimeSeries } from 'pond-ts';
import { BarChart } from './BarChart.js';
import { YAxis } from './YAxis.js';
import type { SelectInfo } from './context.js';

/**
 * **Chart fixtures for the selection matrix** (`Interactions/Selector/*`,
 * `Interactions/MultiSelector/*`).
 *
 * The selection stories are a **matrix**: one feature set × one fixture per
 * chart type, generated by `selection-stories.tsx`. This file supplies the
 * columns; that file supplies the rows.
 *
 * **Why generated rather than hand-written per column.** A matrix is only a
 * review instrument if a difference between two columns is a difference in the
 * *library* — if each cell were written by hand, a divergence could equally be
 * someone having wired the story differently, and you'd have to read both to
 * know which. Generating every cell from one definition makes any visible
 * difference a real one. (It also makes a new chart type ~10 lines instead of a
 * dozen near-copies, which is what makes widening the matrix survivable.)
 *
 * That is not hypothetical: half a built matrix already surfaced two defects —
 * categorical hover being ink-only where the time axis claims the whole slot,
 * and `<RangeCursor>` on an ordinal axis suppressing the row's cursor entirely.
 *
 * **Capabilities are declared, not assumed.** `sequence` and `rangeCursor` are
 * absent on fixtures that cannot support them, so the factory omits those
 * stories rather than generating one that silently does nothing. A gap in the
 * matrix is information; a story that renders nothing is a trap.
 */
export interface ChartFixture {
  /** Sub-folder name in the Storybook tree (`Interactions/Selector/<name>`). */
  readonly name: string;
  /** Container props this chart needs — a `range` for a time axis. */
  readonly container: Record<string, unknown>;
  /** The primary y-axis. */
  readonly axis: { id: string; min: number; max: number; label: string };
  /** The layer under test, tagged with `id` (identity — see RFC Q8). */
  renderLayer(id: string): ReactNode;
  /** A second row's axis + layer, for the row-scoping story. */
  readonly secondary: {
    axis: { id: string; min: number; max: number; label: string };
    renderLayer(id: string): ReactNode;
  };
  /** Marks an *external* control can pick — drives the controlled-selection
   *  story, which is the case A1.2 exists to protect. */
  readonly picks: readonly { label: string; info: SelectInfo }[];
  /** How a hit reads in a caption. */
  describe(hit: SelectInfo): string;
  /** A snapping sequence, where the axis has one. Ordinal axes do not. */
  readonly sequence?: () => Sequence;
  /** Whether `<RangeCursor>` draws here — it gates on a continuous x
   *  (`brush.tsx`), so mounting one on a category axis is not just inert, it
   *  takes the row's cursor with it. */
  readonly rangeCursor: boolean;
}

const DAY = 86_400_000;
const D0 = Date.UTC(2026, 6, 1);

// ── Categorical ────────────────────────────────────────────────────────────

const SERVICES = [
  { label: 'api', value: 2.7 },
  { label: 'auth', value: 1.4 },
  { label: 'cache', value: 0.6 },
  { label: 'db', value: 3.2 },
  { label: 'queue', value: 1.05 },
  { label: 'search', value: 0.3 },
];

const ERRORS = [
  { label: 'api', value: 0.9 },
  { label: 'auth', value: 0.2 },
  { label: 'cache', value: 1.6 },
  { label: 'db', value: 0.4 },
  { label: 'queue', value: 1.1 },
  { label: 'search', value: 0.8 },
];

/** A `SelectInfo` for one category — what a legend chip / filter list hands in.
 *  On an ordinal axis the identity is the **mark** (the stable category name),
 *  not the slot index, which is the whole point of `mark` surviving a reorder. */
const svc = (label: string): SelectInfo => ({
  id: 'svc',
  key: 0,
  value: 0,
  color: '#000',
  label,
  mark: label,
});

export const categoricalBars: ChartFixture = {
  name: 'Categorical',
  container: {},
  axis: { id: 'v', min: 0, max: 3.6, label: '' },
  renderLayer: (id) => <BarChart categories={SERVICES} id={id} gap={6} />,
  secondary: {
    axis: { id: 'e', min: 0, max: 2, label: 'errors' },
    renderLayer: (id) => (
      <BarChart categories={ERRORS} id={id} gap={6} as="warn" />
    ),
  },
  picks: SERVICES.map((c) => ({ label: c.label, info: svc(c.label) })),
  describe: (hit) => hit.mark ?? hit.label,
  // No `sequence`: a time bucketing over ordinal slots is meaningless.
  // No `rangeCursor`: it gates on a continuous x.
  rangeCursor: false,
};

// ── Time axis ──────────────────────────────────────────────────────────────

/** Thirty daily interval bars — a deterministic random-ish walk. */
const daily = () =>
  new TimeSeries({
    name: 'daily',
    schema: [
      { name: 'timeRange', kind: 'timeRange' },
      { name: 'v', kind: 'number' },
    ] as const,
    rows: Array.from({ length: 30 }, (_, i) => [
      [D0 + i * DAY, D0 + (i + 1) * DAY],
      6 + 4 * Math.sin(i / 3) + 1.5 * Math.sin(i * 1.7),
    ]) as [[number, number], number][],
  });

/** A second daily series for the row-scoping story. */
const dailyErrors = () =>
  new TimeSeries({
    name: 'errs',
    schema: [
      { name: 'timeRange', kind: 'timeRange' },
      { name: 'v', kind: 'number' },
    ] as const,
    rows: Array.from({ length: 30 }, (_, i) => [
      [D0 + i * DAY, D0 + (i + 1) * DAY],
      1 + Math.abs(Math.sin(i * 0.9)) * 1.4,
    ]) as [[number, number], number][],
  });

const isoDay = (t: number) => new Date(t).toISOString().slice(5, 10);

export const timeBars: ChartFixture = {
  name: 'BarChart',
  container: { range: [D0, D0 + 30 * DAY] },
  axis: { id: 'v', min: 0, max: 12, label: '' },
  renderLayer: (id) => (
    <BarChart series={daily()} column="v" axis="v" id={id} />
  ),
  secondary: {
    axis: { id: 'e', min: 0, max: 3, label: 'errors' },
    renderLayer: (id) => (
      <BarChart series={dailyErrors()} column="v" axis="e" id={id} as="warn" />
    ),
  },
  // A time hit's identity is its `key` (the bar's begin), so an external
  // control picks by timestamp rather than by name.
  picks: [0, 4, 9].map((i) => ({
    label: isoDay(D0 + i * DAY),
    info: {
      id: 'svc',
      key: D0 + i * DAY,
      value: 0,
      color: '#000',
      label: 'v',
    },
  })),
  describe: (hit) => isoDay(hit.key),
  /**
   * **The bucket must be coarser than the bar**, or the snap has nothing to do
   * and the story silently demonstrates nothing: these are *daily* bars, so a
   * `'1d'` sequence would bucket exactly one bar each and look identical to the
   * freeform sweep. A week spans seven, which is visible. Anchored at the first
   * bar so the buckets line up with the data rather than with the epoch.
   */
  sequence: () => Sequence.every('7d', { anchor: D0 }),
  rangeCursor: true,
};

/** Every column of the matrix, in tree order. */
export const FIXTURES = [categoricalBars, timeBars] as const;

/** Shared caption styling, so every cell reads identically. */
export const caption = {
  font: '13px system-ui',
  color: '#667',
  marginTop: 4,
  maxWidth: 640,
} as const;

export { DAY, D0 };
